
CFLAGS = -g -O -fno-inline  -fopenmp -DPACKAGE_NAME=\"ptmcmc\" -DPACKAGE_TARNAME=\"ptmcmc\" -DPACKAGE_VERSION=\"1.0\" -DPACKAGE_STRING=\"ptmcmc\ 1.0\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DHAVE_CXX11=1
CXX = /opt/local/bin/g++-mp-8
